# Generated by Django 5.2.10 on 2026-01-14 16:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('delivery_address', models.TextField(help_text='Full delivery address')),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_state', models.CharField(max_length=50)),
                ('delivery_zip', models.CharField(max_length=10)),
                ('delivery_notes', models.TextField(blank=True)),
                ('drop_off_date', models.DateField()),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('rental_months', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('monthly_rate', models.DecimalField(decimal_places=2, help_text='Rate at time of booking', max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, help_text='Delivery fee at time of booking', max_digits=10)),
                ('pickup_fee', models.DecimalField(decimal_places=2, default=0, help_text='Pickup fee (charged when pickup scheduled)', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=200)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('pickup_scheduled', 'Pickup Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('confirmation_sms_sent', models.BooleanField(default=False)),
                ('drop_off_reminder_sent', models.BooleanField(default=False)),
                ('pickup_reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_pickup_date', models.DateField()),
                ('pickup_address', models.TextField(blank=True, help_text='If different from delivery address')),
                ('pickup_notes', models.TextField(blank=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('pickup_email_sent', models.BooleanField(default=False)),
                ('pickup_sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_request', to='bookings.booking')),
            ],
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'drop_off_date'], name='bookings_bo_status_91fa3f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer_email'], name='bookings_bo_custome_f6e328_idx'),
        ),
    ]
