# Generated by Django 5.2.10 on 2026-01-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_fee',
        ),
        migrations.AddField(
            model_name='booking',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Transport/delivery+removal fee at time of booking', max_digits=10),
        ),
    ]
