# Generated by Django 5.2.10 on 2026-01-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='country_code',
            field=models.CharField(default='+1', help_text='Phone country code', max_length=5),
        ),
    ]
