# Generated by Django 5.2.10 on 2026-01-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_distance_km',
            field=models.IntegerField(blank=True, help_text='Distance from business to delivery location in kilometers', null=True),
        ),
    ]
