# Generated by Django 5.2.10 on 2026-01-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsetting',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Flat fee for delivery and removal (covers both)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingsetting',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=79.0, help_text='Legacy - use transport_fee instead', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricingsetting',
            name='pickup_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=79.0, help_text='Legacy - use transport_fee instead', max_digits=10, null=True),
        ),
    ]
