# Generated by Django 5.2.10 on 2026-01-16 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceBasedFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_distance_km', models.IntegerField(help_text='Minimum distance in kilometers')),
                ('max_distance_km', models.IntegerField(help_text='Maximum distance in kilometers (use 999 for unlimited/default)')),
                ('fee', models.DecimalField(decimal_places=2, help_text='Fee in dollars for this distance range', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(help_text="e.g., 'Within 30 km', '30-100 km', 'Beyond 100 km'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_distance_km'],
                'constraints': [models.UniqueConstraint(fields=('min_distance_km', 'max_distance_km'), name='unique_distance_range')],
            },
        ),
    ]
